name: Test

on:
  push:
    paths:
      - '**.php'
      - 'composer.json'
    branches:
      - 'main'
  pull_request:
    paths:
      - '**.php'
      - 'composer.json'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
        - '8.5'
    name: PHP ${{ matrix.php }} Test

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, json, mbstring, xml, xmlwriter
          tools: phpcs
          coverage: pcov
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup problem matchers for PHP syntax check
        run: echo "::add-matcher::.github/php-syntax.json"

      - run: |
          ! find . -type f -name '*.php' -exec php -l '{}' \; 2>&1 |grep -v '^No syntax errors detected'

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run phpcs
        run: composer cs

      - name: Run PHPStan
        run: composer phpstan

      - name: Execute tests
        run: |
          set +e
          output=$(composer test -- --coverage-clover=coverage.xml 2>&1)
          exit_code=$?
          echo "$output"
          # If the only issue is the cache directory warning, ignore the exit code.
          if echo "$output" | grep -q "No cache directory configured, result of static analysis for code coverage will not be cached"; then
            echo "Ignoring known PHPUnit warning about missing cache directory."
            exit 0
          else
            exit $exit_code
          fi

      - name: Run codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
